"""Add tags

Revision ID: 328ed236c3a9
Revises: 4989e1d6bdda
Create Date: 2025-05-14 23:22:31.255673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328ed236c3a9'
down_revision = '4989e1d6bdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
