"""remove temp field

Revision ID: 343b956471a9
Revises: ee6abb6bb0d5
Create Date: 2025-05-16 04:35:09.100060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343b956471a9'
down_revision = 'ee6abb6bb0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.drop_column('temp_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_field', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
