"""Add rating

Revision ID: 4989e1d6bdda
Revises: c435cc37aca5
Create Date: 2025-05-12 11:16:13.381710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4989e1d6bdda'
down_revision = 'c435cc37aca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_event_attendance_marked_by',  # ЯВНОЕ ИМЯ ДЛЯ FOREIGN KEY
            'user',
            ['marked_by_id'],
            ['id']
        )

    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rating', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('event_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_event_attendance_marked_by',  # ТО ЖЕ ИМЯ, ЧТО И В upgrade()
            type_='foreignkey'
        )
        batch_op.drop_column('marked_by_id')

    # ### end Alembic commands ###