"""Update tags 2

Revision ID: 7b7e8cdd1d4c
Revises: 328ed236c3a9
Create Date: 2025-05-15 00:46:57.459789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7b7e8cdd1d4c'
down_revision = '328ed236c3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
